### ISSUE TITLE
Compile error #1113  on driverAtmelRFInterface.cpp by armcc

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/atmel-rf-driver#11]
driverAtmelRFInterface.cpp", line 50: Error:  #1113: Inline assembler not permitted when generating Thumb code

` __asm__ volatile ("nop");`
      ^
I modified the local code as below to fix:
```
#if defined(__CC_ARM)
        __nop();
#else
    __asm__ volatile ("nop");
#endif
```

**Comment by 0xc0170** [comment]
@cyliangtw You can also use https://github.com/ARMmbed/cmsis-core/blob/master/cmsis-core/core_cm0.h#L79, but I believe we should add asm to compiler-polyfill. I'll add an issue there

**Comment by cyliangtw** [comment]
I used core_cm0.h firstly but still got #1113 error. Finally, refer to **4.1.2. Restrictions on inline assembly operations**  at [infocenter.arm.com/help] (http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0205f/Chdgddcj.html)

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: ONME-2103
