### ISSUE TITLE
driverRFPhy.c general for all RF

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/atmel-rf-driver#21]
For RF solution, it needs RF driver and base-band code with HW independent scenario or control (for ex: hopping). So far, sal-stack-nanostack seems cover base-band code.
In driverRFPhy.c, except `rf_init_phy_mode() & rf_scale_lqi()`, other functions seem general for all RF.
Do you consider to isolate driverRFPhy to let RF driver concisely ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2607

**Comment by SeppoTakalo** [comment]
Hi @cyliangtw 

The code in the driverRFphy.c reflect to the state machine that Atmel's RF chip has. It might be generic, but not generic enough to cover other RF chip vendors.
We therefore have no plan to refactor it to two parts.

Br. Seppo
