### ISSUE TITLE
Can't get frame received interrupt

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/atmel-rf-driver#35]
On NUC472 platform, atmel-rf-driver could work in mbed OS 3.0, however it can't get any frame received interrupt in mbed OS 5.0 .
So, I measured I2C, SPI & IRQ pins. I2C & SPI read/write 1st 36 bytes are the same with K64F, thus pins are fine. More,` rf_if_interrupt_handler()` & `rf_handle_tx_end()` are invoked, it reveals IRQ pin also working fine. I tried to add 25000ns delay in` rf_if_spi_exchange()`, K64F also suffered "`no received interrupt`" symptom.
 
I suspect the timing of sending SPI data sequence into RF was changed in RTOS version and it seems impact atmel RF behavior. Should I tune any parameter in this driver to fulfill NUC472 platform ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2741

**Comment by hasnainvirk** [comment]
Hi @cyliangtw ,

Can you please elaborate your setup a bit here. What application are you using ?

**Comment by hasnainvirk** [comment]
@cyliangtw Please also test if you are seeing the same issue with mbed-os-5.1.3 release.

**Comment by cyliangtw** [comment]
Hi @hasnainvirk ,
I used mbed-os-example-mesh-minimal to verify mesh feature.
The mbed_app.json as below:
```
{
    "config": {
        "trace": true
        },
    "target_overrides": {
        "*": {
            "target.features_add": ["IPV6", "COMMON_PAL"],
            "mbed-mesh-api.6lowpan-nd-channel-page": 0,
            "mbed-mesh-api.6lowpan-nd-channel": 12,
            "mbed-mesh-api.6lowpan-nd-channel-mask": "(1<<12)",
            "mbed-mesh-api.thread-config-panid": "0xDEFA",
            "mbed-mesh-api.thread-config-channel": 12,
            "mbed-trace.enable": true
       },
       "NUC472": {
			"atmel-rf.spi-mosi": "A2",
			"atmel-rf.spi-miso": "A1",
			"atmel-rf.spi-sclk": "A4",
			"atmel-rf.spi-cs": "A3",
			"atmel-rf.spi-rst": "D5",
			"atmel-rf.spi-slp": "D7",
			"atmel-rf.spi-irq": "D9",
			"atmel-rf.i2c-sda": "D14",
			"atmel-rf.i2c-scl": "D15"			
        }
    }
}
```

**Comment by hasnainvirk** [comment]
Hi @cyliangtw Are you using this kind of radio shiled ? Or you have some other custom radio shield under your posession ?
https://firefly-iot.com/product/firefly-arduino-shield-900mhz/

**Comment by hasnainvirk** [comment]
@cyliangtw If you have a similar rf shield and you have not rewired anything, then assigning "Ax" pins does not make sense as they are not connected.

**Comment by cyliangtw** [comment]
I used firefly-shield-board-2.4Ghz.
In mbed OS 3.0 without RTOS, it could work fine on NUC472 but it can't work well in OS 5.1.3 .

**Comment by hasnainvirk** [comment]
@cyliangtw If you used that shield  then it's beyond me how you got it working with the pins set defined above. Because AnalogIn pins, i.e., A* are not connected on this shield. I checked the data sheet for the MCU and yes all the pins are multi fucntion, you can configure A2, A1 and A4 for SPI0. But the thing is these pins are not connected on the firefly shield. What if you try with default pin set ? I mean Just remove the pin map from your mbed_app.json and try to run ?

**Comment by cyliangtw** [comment]
The default pin set is for K64F board.
So, I need to fly-wire SPI & I2C pins on NUC472 board. I did the same thing in mbed OS 3.0 and could work fine. 
In mbed OS 5, I verified first several SPI & I2C R/W data set and the result is the same with K64F's.
Furthermore checking, got RF PHY_RSSI return value is always 0 "FCS is not valid", is it normal ?

**Comment by hasnainvirk** [comment]
@cyliangtw Do you have a pull up in your circuit ?

**Comment by cyliangtw** [comment]
@hasnainvirk No pull up in my circuit. In the comparison my board v.s K64F, the first 1000 spi data set are the same. The difference is starting from 1057th, the snippet of 1057th ~1065th as below:
**My board:**
```
MOSI: 0xC2;  MISO: 0x00
MOSI: 0x09;  MISO: 0xC2
MOSI: 0x81;  MISO: 0x00
MOSI: 0x00;  MISO: 0x09
MOSI: 0x97;  MISO: 0x00
MOSI: 0x00;  MISO: 0x00
MOSI: 0xD7;  MISO: 0x00
MOSI: 0x00;  MISO: 0xD7
MOSI: 0xC2;  MISO: 0x00

```
**K64F:** 
```
MOSI: 0x81;  MISO: 0x00	
MOSI: 0x00;  MISO: 0x09	
MOSI: 0x81;  MISO: 0x00	
MOSI: 0x00;  MISO: 0x09	
MOSI: 0x81;  MISO: 0x00	
MOSI: 0x00;  MISO: 0x09	
MOSI: 0x81;  MISO: 0x00	
MOSI: 0x00;  MISO: 0x09	
MOSI: 0x81;  MISO: 0x00	
```

**Comment by hasnainvirk** [comment]
@kjbracey-arm Can you please look into it ?

**Comment by kjbracey-arm** [comment]
Are you sure those traces are the right way around? Looks like it's the second one "K64F" not working. What were the preceding values?

Looking at those, I'd say the bottom one has forgotten to send the "C2 09" (which means STATE:=PLL_ON), and is then waiting indefinitely for the STATUS register to read back PLL_ON.

**Comment by cyliangtw** [comment]
@kjbracey-arm 
The second one K64F is working and could get IPv6 address & MAC address.

About the preceding values, please refer to the attachment.
[spi_log.txt](https://github.com/ARMmbed/atmel-rf-driver/files/467246/spi_log.txt)

**Comment by kjbracey-arm** [comment]
The full SPI trace suggests it isn't getting the TX finished interrupt. I don't see the read of the status register that I'd expect from rf_if_irq_task_process_irq().

It seems that the CCA done interrupt is occurring, but then the second interrupt for TX done isn't.

A latching problem in the interrupt HAL? The interrupt should be set rising-edge sensitive. Maybe it's not being cleared correctly after the first interrupt?

**Comment by cyliangtw** [comment]
@kjbracey-arm 
Thanks of your suggestions, after dig the wave form, the root cause is IRQ latency too long, I will reduce our IRQ latency of GPIO debounce time.
