### ISSUE TITLE
Cannot open source input file "nanostack/platform/arm_hal_phy.h": No such file or directory

### ISSUE THREAD

**Issue by nick-yang-nj** [ARMmbed/atmel-rf-driver#41]
I am following the procedures from here:
https://docs.mbed.com/docs/building-an-internet-connected-lighting-system/en/latest/4_connectivity/

The mbed-os version is 5.1. I got this error:
Cannot open source input file "nanostack/platform/arm_hal_phy.h": No such file or directory

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2794

**Comment by SeppoTakalo** [comment]
Hi @nick-yang-nj 
What application is used?
Is your application enabling `FEATURE_IPV6` and `FEATURE_COMMON_PAL`

The Atmel RF driver requires Nanostack to be enabled because it implements its driver API.

**Comment by nick-yang-nj** [comment]
Hi, Seppo.

I am new to mbed. I am just trying to build the connected light example. I am using ESP8266 WiFi module. I don't think I need IPV6. I don't know what COMMON_PAL is.
How to enable nanostack in mbed OS? (I am using ARM online compiler and could not find how to enable/disable features).

Thanks,

Nick

**Comment by SeppoTakalo** [comment]
@janjongboom 
Can you check why your examples are not working anymore?

Thank you.

**Comment by janjongboom** [comment]
@nick-yang-nj, workaround: remove IPv4, IPv6 from mbed_app.json. Remove the `atmel-rf-driver` folder from easy-connect. Then it should build for ESP8266.

Will update instructions in the connected lights article.

**Comment by SeppoTakalo** [comment]
Closing as this is not valid for mbed OS 5.2
