### ISSUE TITLE
Missing mbed_lib.json

### ISSUE THREAD

**Issue by devran01** [ARMmbed/atmel-rf-driver#47]
The mbed_lib.json file is missing in the repository after refactoring the atmel rf driver. In order to build the border router (thread or 6lowpan) for Raspberry Pi HAT, radio reset pin needs to be re-configured to a different pin. When mbed_lib.json was available, i was able to re-configure the radio reset pin using mbed_app.json, which is not possible anymore. Is there a particular reason why mbed_lib.json is removed? or the is the library config is moved to a different place?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2877

**Comment by hasnainvirk** [comment]
[Reiterating Jira Comment]
@devran01  The driver was changed by @c1728p9 . Ofcourse it made perfect sense to change it as now a Radio selection can be made runtime without any conflicts. However, yes, in the process we lost the mbed_lib.json bit. Currently, the constructor call to NanostackRFPhyAtmel, i.e,

NanostackRfPhyAtmel(PinName spi_mosi, PinName spi_miso,
PinName spi_sclk, PinName spi_cs, PinName spi_rst, PinName spi_slp, PinName spi_irq,
PinName i2c_sda, PinName i2c_scl);

takes the pin names in. So the application do have control over PinNames. You can define use the constructor to have whichever pin you like.

[Closing the ticket as not a real issue. @devran01 was satisfied with the answer and asked to close the ticket.]
