### ISSUE TITLE
ACK are missed on STM boards because of SPI exchange that are no fast enough

### ISSUE THREAD

**Issue by pmancele** [ARMmbed/atmel-rf-driver#53]
I'm opening this issue in continuity of this one where we identified the source of the probleme : https://github.com/ARMmbed/mbed-os/issues/4246

The problem is detailled in the last comments, starting with the comment of **kjbracey-arm** of may the 11th.

To summarize:

After sending a frame to the ATMEL buffer, the MCU should wait for a TRX_END interrupt, indicating that the transfer is done.
When this interrupt is detected, the MCU should change the state of the ATMEL 6LoWPAN chip to RX_AACK_ON within the 192µs, in order to be ready to receive the ACK.

But on STM MCU that we used (STM32L476ZG, NUCLEO_L476RG, NUCLEO_F401RE) the Time between 2 SPI exchange (CMD and response for example) is about 3 times longer on ST boards that the K64F.
Because of that we manage to realize the turnover in about 300µs which is too much ! So all the ACK are missed and the chip send every frame 5 times before giving up.

Bellow are some screenshot of the first SPI transaction that happen just after the TRX_END interrupt (when the board try to answer a PING). As you can see it is faster on the K64F. We can also see that it depends more on the systemcoreclock than the SPI frequency:

* K64F at 120 MHZ, with SPI at 7.5 MHz:
![k64f zoom](https://cloud.githubusercontent.com/assets/25764849/25958190/50442214-3670-11e7-879e-d6b3ba6e23e2.png)
* STM32L476 at 60MHz, with SPI at 7.5MHz:
![zoom stm32l476 at 60mhz spi at 7 5](https://cloud.githubusercontent.com/assets/25764849/25958222/61827c1a-3670-11e7-87d4-d15784b5da2e.png)
* STM32L476 at 80MHz, with SPI at 5MHz:
![zoom stm32l476 at 80mhz spi at 5](https://cloud.githubusercontent.com/assets/25764849/25958250/714452b8-3670-11e7-9e78-9dd4c1fec8eb.png)

**Comment by 0xc0170** [comment]
@bcostm @adustm  @LMESTM @jeromecoutant

**Comment by LMESTM** [comment]
@pmancele - could you share the driver code that is using SPI ? Or at least explain which SPI APIs are being used and in which sequence. 

A first-level answer:
As you are showing on the screenshots, most of the time involved here is not spent in the SPI transfer itself, so this means this is spent running SW on the MCU.  STM32L476ZG MCU is a low power MCU and is running at a slower speed (60/80MHz vs. 120MHz of K64F, wihich explains by itself a part of the difference). Another part of the explanation is that SPI byte per byte transfer is not very efficient, and STM32 driver uses a generic HAL API which requires many registers setup for each transfer, so better to group transfer as much as possible  Another part that would impact performances is the C++ driver and lock mechanism.

**Comment by kjbracey-arm** [comment]
The code uses the mbed SPI::write(), which calls spi_master_write(), which is only 1-byte-at-time.

I'll paste in my comments from the other issue for easy reference:

Okay, that set-up time is huge. If we were to offer a multi-byte transfer API, for those few accesses, it would only help a bit. The register accesses are only 2- or 3-byte bursts. It looks like it would still take too long.

There is also the curious fact that the 60MHz version is not proportionately slower. Surely it should take 4/3 as long as the 80MHz between transfers, not virtually twice as long? Does that indicate some problem?

My approach to tackle this would be three-pronged:

  * Add multi-byte synchronous master transfer API to mbed HAL
  * Update Atmel driver to use this API
  * Request ST to do whatever they can to reduce their SPI transfer setup time.

There may also be some scope to reduce number of transfers in the driver's critical path (eg use the option that gives automatic status output during the register address byte) but without some improvement from ST, I don't see we'll ever get to 192µs.

The alternative "last resort" would be a driver change that allows it to use automatic mode, but that's non-trivial and we don't want to lose the manual mode capability, so it would increase driver complexity not reduce it. (The manual mode permits more tuning of transmission timing, and we've found the 802.15.4 specced behaviour used by the hardware doesn't work well in some environments that we target with the Atmel chip).

**Comment by pmancele** [comment]
@LMESTM Before finally setting the state to RX_AACK_ON, the drivers performs 9 SPI transactions (6 reads and 3 writes) by calling the following functions:
```c
static void rf_if_write_register(uint8_t addr, uint8_t data)
{
  uint8_t cmd = 0xC0;
  CS_SELECT();
  rf_if_spi_exchange(cmd | addr);
  rf_if_spi_exchange(data);
  CS_RELEASE();
}
static uint8_t rf_if_read_register(uint8_t addr)
{
  uint8_t cmd = 0x80;
  uint8_t data;
  CS_SELECT();
  rf_if_spi_exchange(cmd | addr);
  data = rf_if_spi_exchange(0);
  CS_RELEASE();
  return data;
}
```
`rf_if_spi_echange()` directly call the SPI::write api of mbed-os as explained kjbracey-arm

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3074

**Comment by LMESTM** [comment]
Few answers:

>  There is also the curious fact that the 60MHz version is not proportionately slower. Surely it should take 4/3 as long as the 80MHz between transfers, not virtually twice as long? Does that indicate some problem?

In the clock configuration where you've reduced ARM processor clock 60MHz, you've also reduced APB2clk at 48MHz compared to default 80MHz. As most of the activity in this use case is about accessing SPI registers, the impact of reducing APB2CLK is very important and most probably , also a cause of this drop in performance, combined with processor clocks being decreased as well.

> My approach to tackle this would be three-pronged:
> Add multi-byte synchronous master transfer API to mbed HAL
> Update Atmel driver to use this API

sounds a good first step to me

> Request ST to do whatever they can to reduce their SPI transfer setup time.

I take the point and will see what I can do.

**Comment by kjbracey-arm** [comment]
There's an obvious missing extra part of that first step - ST would need to implement the API extension. Seems like it would be trivial though.

**Comment by 0xc0170** [comment]
> There's an obvious missing extra part of that first step - ST would need to implement the API extension. Seems like it would be trivial though.

This one should help? https://github.com/ARMmbed/mbed-os/pull/4207 (still waiting for adding method for block writes).

**Comment by kjbracey-arm** [comment]
Had my hopes up there for a moment. The discussion there seems to have agreed that a block write API would be a Good Thing, but I believe they were only considering the layer above the HAL, not the HAL itself.

In our case, we have already deactivated the locks on the SPI by overriding them with null functions, so I believe we've effectively already gained the speed gain discussed there.

**Comment by pmancele** [comment]
@LMESTM No, i reduced the ARM processor clock to 60MHz especially to get 60MHz on APB2clk too. Indeed to obtain the SPI speed, the APB2clk is divided by power of 2. So 60MHz on APB2clk allowed me to reach 7.5MHz for SPI (60/8) which is the fastest frequency that the ATMEL chip is accepting.

But this didnt improve the turnaround time, because there is a lots of time lost between two byte transfer.

As you said  SPI byte per byte transfer is not very efficient, and STM32 driver requires many registers setup for each transfer, so better to group transfer as much as possible.

**Comment by LMESTM** [comment]
@pmancele I've pushed a branch with a patch (https://github.com/ARMmbed/mbed-os/issues/4246) that should show improvement in STM32 driver side. But I'm still in favor of multi-byte synchronous master transfer API, and I'd definitely deliver the STM32 port for it.

**Comment by pmancele** [comment]
@LMESTM I've tested the patch and there is a big improvement indeed.
With the STM32L476 at 80MHz, it manage to realize the turnaround within 125µs (VS 278µs previously) when i compile with the RELEASE profile. But if i compile with the DEBUG profile it takes 245 µs which is still too much.
Moreover, for lowpower application, the clock may be under 80MHz so we still need to improve the communication by grouping the transfer as much as possible!

Nevertheless, thank you for this improvement!

* STM32L476 at 80 MHz, RELEASE profile (125µs):
![turnaround stm32l476 80mhz release profile](https://cloud.githubusercontent.com/assets/25764849/26101086/369895b6-3a30-11e7-8f70-3de51aaa0359.png)
*STM32L476 at 80MHz, DEBUG profile (247µs):
![turnaround stm32l476 80mhz with new spi api](https://cloud.githubusercontent.com/assets/25764849/26101093/3b76df20-3a30-11e7-904d-9fa9697eae25.png)

**Comment by kjbracey-arm** [comment]
I see one wrinkle with adding a bulk transfer API - the Atmel chip does require 250ns inter-byte spacing during the transfer. (It's currently getting plenty!)

We'd presumably need an API to control that. Is byte spacing an unusual requirement? We don't seem to have any timing controls for the existing asynchronous API.

**Comment by kjbracey-arm** [comment]
I've been looking at the driver, and I think I can shave a few accesses off:

* Configure the chip to auto-return TRX_STATUS when addressing it
* Pick up that TRX_STATUS when reading IRQ_STATUS, and pass along
* Don't manipulate IRQ_MASK
* Keep a soft copy of XAH_CTRL_1

**Comment by kjbracey-arm** [comment]
I believe the core problem here is resolved by https://github.com/ARMmbed/mbed-os/pull/4375. Can you confirm?

General Atmel driver improvements (including trying to use the new block transfer API) are ongoing, but I think this issue can be closed.

**Comment by pmancele** [comment]
It is resolved yes, but only if you build with the release profile as explained pleviously. 
With some driver improvements (which are ongoing as you said) we may be able to fully resolve the problem.

**Comment by pmancele** [comment]
@kjbracey-arm maybe we could add a link to the ongoing driver improvements and close this issue ?

**Comment by kjbracey-arm** [comment]
@pmancele - I have this PR ready to be merged. Could you try it out?

https://github.com/ARMmbed/atmel-rf-driver/pull/58

**Comment by pmancele** [comment]
I will try it asap !
Thank you

**Comment by kjbracey-arm** [comment]
Note that that PR has an explicit "run at max clock speed on TARGET_STM" in its JSON - that's on the assumption that the STM block API is really byte-at-a-time, so it doesn't need to drop to 3.75MHz to have sufficient byte spacing.

Might be worth you checking (a) whether that's activating correctly and (b) whether it would still work without it.

Having that there does mean if STM ever update their HAL to do proper burst writes, it would break the driver until the JSON was changed, so it might be better if we could live without it.

**Comment by pmancele** [comment]
I just try your branch and it seems way better indeed !

It does not miss ACK anymore even if compiled using Debug mode.

The number of operations has been significantly reduced as you can see on the screenshot bellow, which represent the turnaround operations before receiving the ACK, as described in my previous comments.
 
![image](https://user-images.githubusercontent.com/25764849/32383861-73e29858-c0b9-11e7-8c66-b3be45b67534.png)
It takes less than 80 µs on this screenshot to realise the turnaround (vs 140 previously).

SPI speed 5Mhz, SystemCoreClock 80 Mhz
Typical space between 2 bytes 1,3 µs

Should i try something else ?

**Comment by kjbracey-arm** [comment]
No, thanks for the feedback. But was this on the Atmel RF233 (2.4GHz) or RF212 (sub-GHz)?

**Comment by pmancele** [comment]
Atmel RF233 plugged on a board based on the STM32L496RG MCU

**Comment by kjbracey-arm** [comment]
Performance branch merged - this is resolved
