### ISSUE TITLE
Monitor underrun with a counter

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/atmel-rf-driver#68]
Please consider being able to monitor the underrun condition.

https://github.com/ARMmbed/atmel-rf-driver/blob/28ab8d6450074c378881e028def1e54faf731e99/source/NanostackRfPhyAtmel.cpp#L1106

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3932

**Comment by artokin** [comment]
The comment is a reminder of the underrun condition for the driver developers. Previously there was a trace but it caused other problems. 

Currently we don't have plans for the driver diagnostics.
