### ISSUE TITLE
DEVICE_I2C requirement in atmel-rf-driver

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/atmel-rf-driver#73]
Recently in https://github.com/ARMmbed/atmel-rf-driver/commit/cd49e2ee3e4bc670fdf1948d113c2e451db5b29f the build guard for DEVICE_I2C has been introduced. Most devices use this driver with the AT24MAC chip, but this is not a necessity. You can also run this radio (and the driver) without that chip and provision the MAC in a different way and pass it to the driver via NanostackRfPhyAtmel::set_mac_address(uint8_t *mac).

**Comment by kjbracey-arm** [comment]
> the AT24MAC chip, but this is not a necessity

True in principal, but the driver has never been able to compile if the platform doesn't support I2C at all. 

The patch applied was a quick fix to stop system compilation failures on non-I2C platforms when the driver was not actually needed anyway.

I agree the DEVICE_I2C guard could be finer-grained to produce a working-but-without-builtin-MAC driver. Patches welcome - not sure it will be an immediate priority for our development, as non-I2C targets are few.

**Comment by markus-becker-tridonic-com** [comment]
OK
