### ISSUE TITLE
Do not hard-code pins in the driver

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/atmel-rf-driver#8]
The pins of the driver are hard-coded at the moment:
https://github.com/ARMmbed/atmel-rf-driver/blob/master/source/at24mac.cpp#L33
https://github.com/ARMmbed/atmel-rf-driver/blob/master/source/driverAtmelRFInterface.cpp#L24 ff.

Hard-coding the pins in the driver, makes it hard to re-use the driver. At the moment you cannot compile this driver against a different target than the K64F. E.g. the F429 does not announce the Arduino Pins (related to https://github.com/ARMmbed/target-st-stm32f429i-disco/pull/17 ).

It would be better to use symbolic names given to the driver from the application's or target's config.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/ONME-1695

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: ONME-1995

**Comment by mlnx** [comment]
@SeppoTakalo please comment on this request

**Comment by SeppoTakalo** [comment]
Merged the proposed fix in.
